# Generated by Django 4.2.8 on 2024-01-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("position_type", models.CharField(blank=True, max_length=100)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(max_length=255)),
                ("application_status", models.CharField(max_length=100)),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("follow_up_actions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("job_posting_link", models.URLField()),
                ("reflection", models.TextField(blank=True)),
                ("cover_letter", models.URLField(blank=True)),
                (
                    "skill_set",
                    models.ManyToManyField(blank=True, to="job_application.skill"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("detailed_feedback", models.TextField()),
                (
                    "factors",
                    models.ManyToManyField(blank=True, to="job_application.factor"),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_application.jobapplication",
                    ),
                ),
            ],
        ),
    ]
