# Generated by Django 4.2.8 on 2024-01-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="feedback_link",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
