# Generated by Django 4.2.8 on 2024-01-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_application", "0002_jobapplication_feedback_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="feedback_link",
            new_name="feedback_link_uuid",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="detailed_feedback",
            field=models.TextField(blank=True),
        ),
    ]
