# Generated by Django 4.2.8 on 2024-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
