# Generated by Django 4.2.8 on 2024-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.IntegerField(),
        ),
    ]
