# Generated by Django 4.2.8 on 2024-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_player_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
